export { db, PrismaClient, hasDatabase } from "./client";

// Re-export Prisma types for convenience
export type {
  Company,
  User,
  UserCompanyMembership,
  Role,
  Permission,
  RolePermission,
  AuditLog,
  PipelineStage,
  Lead,
  Account,
  Contact,
  Opportunity,
  Activity,
  Task,
  Quote,
  QuoteLineItem,
  ProductCategory,
  Product,
  PriceList,
  PriceListItem,
  Vendor,
  Warehouse,
  StockItem,
  InventoryMovement,
  SalesOrder,
  SalesOrderLineItem,
  PurchaseOrder,
  PurchaseOrderLineItem,
  Invoice,
  InvoiceLineItem,
  ARLedger,
  APLedger,
  CashFlowEntry,
} from "@prisma/client";

export {
  CompanyType,
  GlobalRole,
  LeadStatus,
  LeadSource,
  AccountType,
  ForecastCategory,
  ActivityType,
  TaskStatus,
  TaskPriority,
  QuoteStatus,
  ProductType,
  VendorStatus,
  MovementType,
  SalesOrderStatus,
  PurchaseOrderStatus,
  InvoiceStatus,
  LedgerEntryType,
  CashFlowType,
} from "@prisma/client";